# docker-compose file for python-application:
version: '3'
services:
  python-app: # service name & you can give any name:
    image: ravivarman46/python-app #yours image name:
    container_name: python-app
    ports:
      - 5000:5000 # port mapping
    volumes:
      - py-vol:/app/

volumes:
  py-vol:
    external: true 
